### ISSUE TITLE
Decide on whether and when to add support for user-uploaded hydrofabrics

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#123]
Track the discussion and decision making process on 
a.) whether this feature is wanted/needed, and 
b.) whether the feature should be part of the FIHM, September, or other deliverable 

Support could be added for user-uploaded hydrofabrics, in addition to those statically supplied at MaaS environment start.  It needs to be established whether this is a desired feature and, if so, on what time table it should be included (in particular, whether it belongs in this FIHM milestone).

**Comment by christophertubbs** [comment]
What would the alternative be? We already have a couple different hydrofabrics floating about, like the one for sugar creek and the one for new england.

I would imagine that this should be somewhat doable since we'd already have to do a similar thing with staging other resources.

Then again, I'm a newcomer so I may be missing something crucial.

**Comment by robertbartel** [comment]
The answer appears to be "yes, but not in the FIHM deliverable."

**Comment by robertbartel** [comment]
Spun off to #129 for tracking in a later milestone.
