### ISSUE TITLE
Upgrade GUI django version

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#209]
In trying to debug some things during development, I noticed that we have pinned the `gui`'s django version to `2.2.28`, the latest stable release of django is [`4.1.2`](https://pypi.org/project/Django/4.1.2/). Is there a reason we have not updated this @christophertubbs / @robertbartel?

https://github.com/NOAA-OWP/DMOD/blob/4b02fee1393ec499f0e1e599f462da6b85d15f71/python/gui/dependencies.txt#L4

**Comment by christophertubbs** [comment]
I have an upgrade for it in the branch I'm working on. There are some things that have to be switched out (mostly switching from `url` objects to `re_path` objects in url routing), but it's not too painful. I imagine the entry in the dependencies is just from a pip freeze.

**Comment by aaraney** [comment]
@christophertubbs, cool cool. Thanks for updating this. Your `pip freeze` assumption is correct.

**Comment by christophertubbs** [comment]
`dependencies.txt` (weird version of `requirements.txt` in `python/gui`) specifies the latest version of 3, but the root `requirements.txt` doesn't specify a version. I'm running that version locally and everything is hunky dory. We probably want to make sure that's updated in the `dependencies.txt` and that it's limited to `~=4.0` since we're good this time but we might get hurt if it decides to pull 5.0+ at some point.

**Comment by aaraney** [comment]
Related question to your comment, @christophertubbs, can we get rid of `dependencies.txt`?

**Comment by christophertubbs** [comment]
Not atm because of how the gui's docker image is built.
