### ISSUE TITLE
Deadcode: dmod communication NWMConfig is currently unused

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#250]
Thoughts on removing this class? It appears it is not used.

https://github.com/NOAA-OWP/DMOD/blob/d725ad77d0052e0b40932349544e6df331d15b89/python/lib/communication/dmod/communication/maas_request/nwm/nwm_config.py#L5

**Comment by robertbartel** [comment]
I'd say not yet. In the beginning, DMOD exclusively supported versions of NWM prior to NextGen, because there was no NextGen at that point.   I don't think DMOD ever officially dropped such support.  It's just broken and without a strong call for its repair.

As part of the continued evolution of the design, functionality for both NWM/WRF-Hydro and NextGen executions stopped working.   Only the NextGen functionality has been fixed to this point, due to development resource availability and prioritization.  Parts of the NWM-related code were altered, though, when that was unavoidable, and making code dead was probably a faster, more minimalist solution for some of that.

It _could_ still be useful to have this working again.   We'd be able to compare output of older NWM versions to NextGen output, for example.  It's just a task much further down on the list.
